sonar.projectKey=Zbr123_Testing-Automation-Silk
sonar.organization=zbr123        # Only for SonarCloud, skip for self-hosted
sonar.pullrequest.provider=GitHub

# PR-specific properties:
sonar.pullrequest.key=${{ github.event.pull_request.number }}
sonar.pullrequest.branch=${{ github.head_ref }}
sonar.pullrequest.base=${{ github.base_ref }}
