sonar.projectKey=Zbr123_Testing-Automation-Silk
sonar.organization=zbr123        # Only for SonarCloud, skip for self-hosted
sonar.pullrequest.provider=GitHub

# Optional project metadata
# sonar.projectName=Testing-Automation-Silk
# sonar.projectVersion=1.0

# Specify your source code location if needed
# sonar.sources=.
# sonar.sourceEncoding=UTF-8
