platformname=Android
appiumport=4725

platformName=Android
platformVersion=11
automationName=UiAutomator2
deviceName=Samsung
androidapk=app-staging-release-universal.apk

browserstack=false
browserstackDevice=Samsung Galaxy S22 Ultra
browserstackOS=12.0
browserStackUser=muhammadzubair_i6VPu8
accessKey=HVn4xyXDnAC7xkvzGgWZ
BROWSERSTACK_APP_ID=bs://29e26702a4edbd3becbcb8883afa8055578aecf6
