name: SonarCloud PR Analysis

on:
  pull_request:
    branches:
      - main # Specify your target branch here (e.g., main, develop, etc.)
      - webdriver-CICD
      - webdriver-browserstack
      - webdriver-BDD
      - webdriver-Qase.io

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # To ensure the entire history is available for accurate analysis

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Run SonarCloud scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=Zbr123_Testing-Automation-Silk
            -Dsonar.projectKey=zbr123
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
            -Dsonar.pullrequest.provider=GitHub
